
areas: ['centenario','la_boca','palermo','cordoba']

DL:
  calidad_aire:
    table_name: 'calidad_aire'
    schema: 'preproduccion'
    delete_row: 'fecha'

  promedio_metricas_por_area_tmp:
    table_name: 'promedio_metricas_por_area_tmp'
    schema: 'preproduccion'

  viajes_transporte_publico:
    table_name: 'viajes_transporte_publico'
    schema: 'preproduccion'
    delete_row: 'fecha'

  aqi_categorias:
    table_name: 'aqi_categorias'
    schema: 'preproduccion'

DW:
  indicador_calidad_aire:
    table_name: 'indicador_calidad_aire'
    schema: 'produccion'
    delete_row: 'fecha'

  top_10_dias:
    table_name: 'top_10_dias'
    schema: 'produccion'
    delete_row: 'fecha'

  top_3_por_mes:
    table_name: 'top_3_por_mes'
    schema: 'produccion'
    delete_row: 'fecha'

  dias_menor_impacto_contaminacion:
    table_name: 'dias_menor_impacto_contaminacion'
    schema: 'produccion'
    delete_row: 'fecha'

  dias_mayor_impacto_contaminacion:
    table_name: 'dias_mayor_impacto_contaminacion'
    schema: 'produccion'
    delete_row: 'fecha'